### ISSUE TITLE
calibration cities & data

### ISSUE THREAD

**Issue by mpadge** [moveability/calibration#1]
See [who3 issue](https://github.com/ATFutures/who3/issues/10)

**Comment by mpadge** [comment]
Cross-link analysis of diurnal variation in pedestrian activity by @robinlovelace in [private repo](https://github.com/ATFutures/ATF-ideas/issues/26)

**Comment by mpadge** [comment]
This is now exclusively a calibration of New York City pedestrian data, for which the repo will be moved to ATFutures, and likely re-named.

**Comment by Robinlovelace** [comment]
Re-opening as it's not yet on the main app. Also, I don't think the data is there: https://github.com/moveability/calibration/releases

https://github.com/moveability/calibration/issues/7#issuecomment-552448603
