### ISSUE TITLE
initial release data

### ISSUE THREAD

**Issue by mpadge** [moveability/calibration#7]
ping @robinlovelace I've just uploaded some *preliminary* NYC flow data from the final model via the first release [here](https://github.com/moveability/calibration/releases). It won't be immediately compatible in format with the previous ones, but instead contains all columns that may be used to turn on and off the selected components of the final model. We probably won't want to do this, but it's good to leave the possibility there. It's a simple `sf` `data.frame`, with lots of `flow*` columns, each scaled to absolute values in pedestrian counts per day. The three-letter abbreviations are:

- "sub" for subway
- "ent" for entertainment
- "dis" for dispersal
- "sus" for sustenance (restaurants, fast foot, groceries, and the like)
- "edu" for education
- "hea" for health
- "tra" for transport (mostly parking)
- "cen" for centrality

The final 2 columns are:
1. "flow" for the aggregate flow that is the direct sum of the final 7 flow columns
2. "flow2" that is a scaled version that can be used for plotting via `mapdeck`. This has also had the top 1,000 values set to the value of the 1,001st flow, because otherwise the colour scale gets mucked up by these extreme values.

For our present purposes, we should only be interested in these latter two columns.

**Comment by Robinlovelace** [comment]
Great to see this come online. Have you tried running it in upthat by putting the file in the inst director? I can give it a go if not. Whoever does it, I think will involve writing a few lines of code so the columns match the expectations. Great work, look forward to seeing the results deployed!

**Comment by mpadge** [comment]
Yep, it works straight away out of the box - although it uses the `"flow"` column, which is entirely saturated by the extreme values along 6th Avenue (very appropriately, I'd say). The `"flow2"` column kinda normalises these out, and look much better, so recommend first set `net$flow <- net$flow2`. I've also just pushed a commit which adds opacity to the lines, with result looking like this:
![image](https://user-images.githubusercontent.com/6697851/68591310-b9f71180-0490-11ea-9397-dac5cc307c6e.png)

**Comment by mpadge** [comment]
closing now, moving any remaining points to #10
